# Generated by Django 4.1 on 2022-08-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Name of the earth material', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of the material', max_length=255, null=True, verbose_name='Description')),
                ('code', models.CharField(blank=True, help_text='Identifier code', max_length=16, null=True, verbose_name='Code')),
                ('url', models.URLField(help_text='URL to the page describing the field on the BGS website', verbose_name='About')),
            ],
            options={
                'verbose_name': 'Earth Materials',
            },
        ),
        migrations.CreateModel(
            name='EarthMaterialProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('earth_materials.earthmaterial',),
        ),
    ]
