# Generated by Django 4.1 on 2022-08-12 16:41

from django.db import migrations
from django.core.management import call_command

fixture = 'data'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='earth_materials') 

class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
