# Generated by Django 3.2.15 on 2022-08-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0002_load_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarthMaterialProxy',
        ),
        migrations.AlterModelOptions(
            name='earthmaterial',
            options={'verbose_name': 'Earth Material', 'verbose_name_plural': 'Earth Materials'},
        ),
    ]
