# Generated by Django 3.2.15 on 2022-08-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0003_auto_20220815_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earthmaterial',
            options={'ordering': ['name'], 'verbose_name': 'Earth Material', 'verbose_name_plural': 'Earth Materials'},
        ),
    ]
