# Generated by Django 3.2.15 on 2022-08-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0004_alter_earthmaterial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earthmaterial',
            options={'verbose_name': 'Earth Material', 'verbose_name_plural': 'Earth Materials'},
        ),
    ]
