# Generated by Django 3.2.15 on 2022-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0005_alter_earthmaterial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthmaterial',
            name='label',
            field=models.CharField(default='', help_text='Short label of the earth material', max_length=255, verbose_name='Label'),
            preserve_default=False,
        ),
    ]
